version: '3.2'

services:
  alpine:
    build:
      context: .
      dockerfile: docker/alpine/Dockerfile
      cache_from:
        - docker.pkg.github.com/gentamura/hello-world-docker-action/alpine
    image: docker.pkg.github.com/gentamura/hello-world-docker-action/alpine
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      cache_from:
        - docker.pkg.github.com/gentamura/hello-world-docker-action/nginx
    image: docker.pkg.github.com/gentamura/hello-world-docker-action/nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html