version: '3.2'

services:
  alpine:
    build:
      context: .
      dockerfile: docker/alpline/Dockerfile
      cache_from:
        - docker.pkg.github.com/hello-world-docker-action/alpline
    image: docker.pkg.github.com/hello-world-docker-action/alpline
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      cache_from:
        - docker.pkg.github.com/hello-world-docker-action/nginx
    image: docker.pkg.github.com/hello-world-docker-action/nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html